language: java
jdk:
  - openjdk11
sudo: required
script:
  - javac -version
  - java -version
  - mvn --version
  - mvn clean test jacoco:report
#notifications:
#  slack:
#    secure:
after_success:
  - mvn coveralls:report 
